# Generated by Django 4.2.7 on 2023-11-16 18:44

import apps.books.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=255, verbose_name="Name of Author")),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Book title")),
                ("publish_date", models.DateField(verbose_name="Publish date")),
                ("isbn", models.CharField(max_length=13)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("authors", models.ManyToManyField(max_length=255, related_name="books", to="books.author")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookCover",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to=apps.books.models.book_cover_directory_path)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="book_covers", to="books.book"
                    ),
                ),
            ],
        ),
    ]
